"""
02_detect_entities.py

For each image, run:
  1. Grounding-DINO object detection (political objects)
  2. InsightFace face detection + gallery matching with quality gating

Output: data/detections/{image_id}.json
{
  "image_id": "...",
  "objects": [{"label": "flag", "bbox": [...], "score": 0.82,
               "subcategory": "thin_blue_line_flag",  # gallery match (null if no/low match)
               "match_score": 0.81, "match_status": "matched"}, ...],
  "faces": [
    {
      "bbox": [x0, y0, x1, y1],
      "det_score": 0.94,          # InsightFace detection confidence (quality proxy)
      "name": "Joe Biden",        # null if low_quality or unknown
      "match_score": 0.71,        # cosine similarity to best gallery match
      "match_status": "matched"   # "matched" | "unknown" | "low_quality"
    }
  ]
}

Usage:
    python 02_detect_entities.py                   # process all unprocessed images
    python 02_detect_entities.py --sample 50       # process 50 random images (for testing)
    python 02_detect_entities.py --eval            # report match statistics from existing JSONs
    python 02_detect_entities.py --build-gallery   # rebuild gallery embeddings from data/gallery/*/

Gallery structure:
    data/gallery/{Person Name}/  ← one subdirectory per identity
        01.jpg                   ← 5–10 reference images (diverse poses/conditions)
        02.jpg
        ...
    data/gallery/embeddings.pkl  ← auto-generated by --build-gallery
"""

import argparse
import json
import pickle
import random
from pathlib import Path

import numpy as np
from PIL import Image
from tqdm import tqdm

from config import (
    DETECTIONS_DIR,
    FACE_QUALITY_THRESHOLD,
    FACE_SIMILARITY_THRESHOLD,
    GALLERY_DIR,
    GDINO_BOX_THRESHOLD,
    GDINO_MODEL,
    GDINO_TEXT_THRESHOLD,
    IMAGES_DIR,
    OBJECT_CLUSTERS_DIR,
    OBJECT_GALLERY_CLIP,
    OBJECT_SIMILARITY_THRESHOLD,
    POLITICAL_OBJECT_QUERIES,
)

# Map a generic GDINO label to its gallery umbrella category (mirrors the build
# notebook's CLUSTER_GROUPS). Labels absent here have no subcategory gallery, so
# they keep only the generic label.
GDINO_LABEL_TO_UMBRELLA = {
    "flag": "flag",
    "banner": "banner_sign", "sign": "banner_sign", "poster": "banner_sign",
    "protest sign": "banner_sign",
    "hat": "headwear", "helmet": "headwear", "cap": "headwear",
}


# ──────────────────────────────────────────────────────────────────────────────
# Grounding-DINO (via HuggingFace transformers)
# ──────────────────────────────────────────────────────────────────────────────

def load_gdino():
    import torch
    from transformers import AutoModelForZeroShotObjectDetection, AutoProcessor
    device = "cuda" if torch.cuda.is_available() else "cpu"
    processor = AutoProcessor.from_pretrained(GDINO_MODEL)
    model = AutoModelForZeroShotObjectDetection.from_pretrained(GDINO_MODEL).to(device)
    model.eval()
    print(f"Grounding-DINO on {device}")
    return processor, model


def detect_objects(image: Image.Image, processor, model,
                   clip_model=None, clip_proc=None, object_gallery=None) -> list[dict]:
    import torch
    # Grounding-DINO expects period-separated queries ending with a period
    query = " . ".join(POLITICAL_OBJECT_QUERIES) + " ."
    inputs = processor(images=image, text=query, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model(**inputs)

    results = processor.post_process_grounded_object_detection(
        outputs,
        inputs["input_ids"],
        threshold=GDINO_BOX_THRESHOLD,        # renamed from box_threshold in transformers 4.51+
        text_threshold=GDINO_TEXT_THRESHOLD,
        target_sizes=[image.size[::-1]],  # (H, W)
    )[0]

    objects = []
    for score, label, box in zip(results["scores"], results["labels"], results["boxes"]):
        x0, y0, x1, y1 = (round(v) for v in box.tolist())
        obj = {
            "label": label,                       # generic GDINO term, e.g. "flag"
            "score": round(float(score), 3),
            "bbox": [x0, y0, x1, y1],
        }
        # Match to a fine-grained political subcategory — but ONLY within this label's
        # umbrella (a 'flag' box is matched against flag subcategories, never a hat one).
        if object_gallery and clip_model is not None and x1 > x0 and y1 > y0:
            umbrella = GDINO_LABEL_TO_UMBRELLA.get(str(label).lower().strip())
            sub_gallery = object_gallery.get(umbrella) or object_gallery.get("_all")
            if sub_gallery:
                crop = _pad_square(image.crop((x0, y0, x1, y1)))
                subcat, sim, status = match_object(
                    embed_crop(crop, clip_model, clip_proc), sub_gallery)
                obj.update({"subcategory": subcat,  # gallery label, e.g. "thin_blue_line_flag"
                            "match_score": round(sim, 3),
                            "match_status": status})
        objects.append(obj)
    return objects


# ──────────────────────────────────────────────────────────────────────────────
# Political-object gallery: CLIP subcategory matching
# Crops are embedded EXACTLY as in build_object_gallery.ipynb (note the pooler_output
# fallback) — otherwise the cosine space won't align with the stored references.
# ──────────────────────────────────────────────────────────────────────────────

def load_clip():
    import torch
    from transformers import CLIPModel, CLIPProcessor
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = CLIPModel.from_pretrained(OBJECT_GALLERY_CLIP).to(device).eval()
    proc = CLIPProcessor.from_pretrained(OBJECT_GALLERY_CLIP)
    print(f"CLIP ({OBJECT_GALLERY_CLIP}) on {device}")
    return model, proc


def load_object_gallery():
    """Return the gallery NESTED by umbrella: {umbrella: {subcategory: [embs]}}.

    Subcategory -> umbrella comes from object_clusters/object_labels.csv (the build
    notebook's output), so matching can be restricted to the box's own umbrella.
    """
    pkl = GALLERY_DIR / "object_embeddings.pkl"
    if not pkl.exists():
        print(f"No object gallery at {pkl} — objects keep generic GDINO labels only.")
        return None
    with open(pkl, "rb") as f:
        flat = pickle.load(f)                       # {subcategory: [embs]}

    sub2cat = {}
    labels_csv = OBJECT_CLUSTERS_DIR / "object_labels.csv"
    if labels_csv.exists():
        import pandas as pd
        df = pd.read_csv(labels_csv)
        df = df[df["subcategory"].astype(str).str.strip().ne("")]
        sub2cat = dict(zip(df["subcategory"].astype(str), df["category"].astype(str)))
    else:
        print(f"  (no {labels_csv.name}; cannot map subcategories to umbrellas — "
              f"matching across ALL subcategories)")

    gallery: dict = {}
    for subcat, embs in flat.items():
        umbrella = sub2cat.get(subcat, "_all")      # "_all" = unknown umbrella -> match anywhere
        gallery.setdefault(umbrella, {})[subcat] = embs
    print(f"Object gallery: {len(flat)} subcategories across umbrellas {list(gallery)}")
    return gallery


def _pad_square(pil_img: Image.Image) -> Image.Image:
    """Center on a black square canvas — mirrors pad_to_square in the build notebook."""
    a = np.array(pil_img.convert("RGB"))
    h, w = a.shape[:2]
    s = max(h, w)
    canvas = np.zeros((s, s, 3), dtype=a.dtype)
    canvas[(s - h) // 2:(s - h) // 2 + h, (s - w) // 2:(s - w) // 2 + w] = a
    return Image.fromarray(canvas)


def embed_crop(pil_img: Image.Image, clip_model, clip_proc) -> np.ndarray:
    import torch
    inp = clip_proc(images=pil_img, return_tensors="pt").to(clip_model.device)
    with torch.no_grad():
        out = clip_model.get_image_features(**inp)
    if torch.is_tensor(out):
        feat = out
    elif getattr(out, "image_embeds", None) is not None:
        feat = out.image_embeds
    elif getattr(out, "pooler_output", None) is not None:
        feat = out.pooler_output
    else:
        feat = out.last_hidden_state.mean(dim=1)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.detach().cpu().numpy().astype(np.float32).ravel()


def match_object(emb: np.ndarray, object_gallery: dict):
    """Best matching subcategory by cosine (refs are L2-normalized). Mirrors _match_embedding."""
    best_name, best = None, -1.0
    for name, refs in object_gallery.items():
        for ref in refs:
            sim = float(np.dot(emb, ref))
            if sim > best:
                best, best_name = sim, name
    if best >= OBJECT_SIMILARITY_THRESHOLD:
        return best_name, best, "matched"
    return None, best, "unknown"


# ──────────────────────────────────────────────────────────────────────────────
# InsightFace face recognition + gallery matching
# ──────────────────────────────────────────────────────────────────────────────

def load_face_app():
    from insightface.app import FaceAnalysis
    # Tries CUDA first, falls back to CPU automatically
    app = FaceAnalysis(
        name="buffalo_l",
        providers=["CUDAExecutionProvider", "CPUExecutionProvider"],
    )
    app.prepare(ctx_id=0)
    return app


def _to_bgr(image: Image.Image) -> np.ndarray:
    """PIL (RGB) → numpy BGR array expected by InsightFace."""
    return np.array(image.convert("RGB"))[:, :, ::-1]


def build_gallery(face_app) -> dict[str, list[np.ndarray]]:
    """
    Embed reference images from data/gallery/{name}/*.{jpg,png} and save
    embeddings to data/gallery/embeddings.pkl.

    Each identity gets a list of L2-normalized embeddings (one per valid image).
    At match time, we take the max similarity across all reference embeddings.
    """
    identity_dirs = sorted(d for d in GALLERY_DIR.iterdir() if d.is_dir())
    if not identity_dirs:
        print(f"No identity directories found in {GALLERY_DIR}")
        print("Create data/gallery/<Person Name>/ with reference images first.")
        return {}

    print(f"Building gallery for {len(identity_dirs)} identities...")
    gallery: dict[str, list[np.ndarray]] = {}

    for identity_dir in tqdm(identity_dirs):
        name = identity_dir.name
        img_paths = sorted(identity_dir.glob("*.jpg")) + sorted(identity_dir.glob("*.png"))
        embeddings = []

        for img_path in img_paths:
            img_bgr = _to_bgr(Image.open(img_path))
            faces = face_app.get(img_bgr)
            if not faces:
                print(f"  [{name}] No face in {img_path.name} — skipping")
                continue
            # Headshots have one subject; take highest-confidence detection
            best = max(faces, key=lambda f: f.det_score)
            if best.det_score < FACE_QUALITY_THRESHOLD:
                print(f"  [{name}] Low quality in {img_path.name} "
                      f"(det_score={best.det_score:.2f}) — skipping")
                continue
            embeddings.append(best.embedding.copy())  # already L2-normalized

        if embeddings:
            gallery[name] = embeddings
            print(f"  [{name}] {len(embeddings)}/{len(img_paths)} images embedded")
        else:
            print(f"  WARNING: No valid embeddings for {name}")

    pkl_path = GALLERY_DIR / "embeddings.pkl"
    with open(pkl_path, "wb") as f:
        pickle.dump(gallery, f)
    print(f"\nGallery saved → {pkl_path}  ({len(gallery)} identities)")
    return gallery


def load_gallery() -> dict[str, list[np.ndarray]]:
    pkl_path = GALLERY_DIR / "embeddings.pkl"
    if not pkl_path.exists():
        raise FileNotFoundError(
            f"Gallery not found at {pkl_path}. Run --build-gallery first."
        )
    with open(pkl_path, "rb") as f:
        return pickle.load(f)


def _match_embedding(
    embedding: np.ndarray,
    gallery: dict[str, list[np.ndarray]],
) -> tuple[str | None, float, str]:
    """
    Find the best matching identity for a face embedding.

    Returns (name, score, status):
      "matched"  — cosine similarity >= FACE_SIMILARITY_THRESHOLD
      "unknown"  — below threshold (face detected but not in gallery)
    """
    best_name, best_score = None, -1.0
    for name, ref_embeddings in gallery.items():
        for ref_emb in ref_embeddings:
            # Both embeddings are L2-normalized → cosine sim = dot product
            sim = float(np.dot(embedding, ref_emb))
            if sim > best_score:
                best_score = sim
                best_name = name

    if best_score >= FACE_SIMILARITY_THRESHOLD:
        return best_name, best_score, "matched"
    return None, best_score, "unknown"


def detect_faces(
    image: Image.Image,
    face_app,
    gallery: dict[str, list[np.ndarray]],
) -> list[dict]:
    faces = face_app.get(_to_bgr(image))
    results = []
    for face in faces:
        x0, y0, x1, y1 = face.bbox.astype(int).tolist()
        quality = float(face.det_score)

        if quality < FACE_QUALITY_THRESHOLD:
            # Face too degraded — skip matching to avoid false positives
            name, score, status = None, None, "low_quality"
        else:
            name, score, status = _match_embedding(face.embedding, gallery)

        results.append({
            "bbox": [x0, y0, x1, y1],
            "det_score": round(quality, 3),
            "name": name,
            "match_score": round(score, 3) if score is not None else None,
            "match_status": status,
        })
    return results


# ──────────────────────────────────────────────────────────────────────────────
# Sample evaluation: report match statistics from existing detection JSONs
# ──────────────────────────────────────────────────────────────────────────────

def run_eval() -> None:
    det_files = list(DETECTIONS_DIR.glob("*.json"))
    if not det_files:
        print("No detection JSONs found. Run detection first.")
        return

    total_faces = matched = low_quality = unknown = 0
    det_scores: list[float] = []
    match_scores: list[float] = []
    identity_counts: dict[str, int] = {}

    for det_file in det_files:
        with open(det_file) as f:
            det = json.load(f)
        for face in det.get("faces", []):
            total_faces += 1
            det_scores.append(face["det_score"])
            status = face["match_status"]
            if status == "matched":
                matched += 1
                match_scores.append(face["match_score"])
                identity_counts[face["name"]] = identity_counts.get(face["name"], 0) + 1
            elif status == "low_quality":
                low_quality += 1
            else:
                unknown += 1

    print(f"\n=== Face Match Statistics ({len(det_files)} images) ===")
    print(f"Total faces detected : {total_faces}")
    if total_faces == 0:
        return

    print(f"  Matched            : {matched:5d}  ({matched/total_faces:.1%})")
    print(f"  Unknown (low sim)  : {unknown:5d}  ({unknown/total_faces:.1%})")
    print(f"  Low quality        : {low_quality:5d}  ({low_quality/total_faces:.1%})")

    if det_scores:
        arr = np.array(det_scores)
        print(f"\nDetection score (all faces):  "
              f"mean={arr.mean():.3f}  median={np.median(arr):.3f}  "
              f"min={arr.min():.3f}  max={arr.max():.3f}")
        near_threshold = ((arr >= FACE_QUALITY_THRESHOLD - 0.1) &
                          (arr < FACE_QUALITY_THRESHOLD + 0.1)).sum()
        print(f"  Faces near quality threshold (±0.1): {near_threshold} "
              f"— consider adjusting FACE_QUALITY_THRESHOLD={FACE_QUALITY_THRESHOLD}")

    if match_scores:
        arr = np.array(match_scores)
        print(f"\nMatch score (matched faces):  "
              f"mean={arr.mean():.3f}  median={np.median(arr):.3f}  "
              f"min={arr.min():.3f}  max={arr.max():.3f}")
        near_threshold = ((arr >= FACE_SIMILARITY_THRESHOLD - 0.05) &
                          (arr < FACE_SIMILARITY_THRESHOLD + 0.05)).sum()
        print(f"  Matches near similarity threshold (±0.05): {near_threshold} "
              f"— consider adjusting FACE_SIMILARITY_THRESHOLD={FACE_SIMILARITY_THRESHOLD}")

    if identity_counts:
        print(f"\nTop matched identities:")
        for name, count in sorted(identity_counts.items(), key=lambda x: -x[1])[:15]:
            print(f"  {count:4d}  {name}")

    # --- Object → subcategory matching (gallery) ---
    total_obj = obj_matched = obj_unknown = 0
    obj_scores: list[float] = []
    subcat_counts: dict[str, int] = {}
    for det_file in det_files:
        with open(det_file) as f:
            det = json.load(f)
        for o in det.get("objects", []):
            total_obj += 1
            status = o.get("match_status")
            if status is None:
                continue                      # gallery wasn't used at detection time
            if o.get("match_score") is not None:
                obj_scores.append(o["match_score"])
            if status == "matched":
                obj_matched += 1
                subcat_counts[o["subcategory"]] = subcat_counts.get(o["subcategory"], 0) + 1
            else:
                obj_unknown += 1

    print(f"\n=== Object Subcategory Match ({len(det_files)} images) ===")
    print(f"Total objects detected : {total_obj}")
    if obj_scores or obj_matched or obj_unknown:
        scored = obj_matched + obj_unknown
        print(f"  Matched            : {obj_matched:5d}  ({obj_matched / max(scored,1):.1%} of gallery-scored)")
        print(f"  Unknown (low sim)  : {obj_unknown:5d}  ({obj_unknown / max(scored,1):.1%})")
        if obj_scores:
            arr = np.array(obj_scores)
            print(f"\nObject match score (all scored objects):  "
                  f"mean={arr.mean():.3f}  median={np.median(arr):.3f}  "
                  f"min={arr.min():.3f}  max={arr.max():.3f}")
            near = ((arr >= OBJECT_SIMILARITY_THRESHOLD - 0.05) &
                    (arr < OBJECT_SIMILARITY_THRESHOLD + 0.05)).sum()
            print(f"  Scores near threshold (±0.05): {near} "
                  f"— tune OBJECT_SIMILARITY_THRESHOLD={OBJECT_SIMILARITY_THRESHOLD}")
            # histogram to read the keep/reject boundary at a glance
            hist, edges = np.histogram(arr, bins=10, range=(0.0, 1.0))
            for h, lo in zip(hist, edges[:-1]):
                print(f"    {lo:.1f}-{lo + 0.1:.1f}: {'#' * int(40 * h / max(hist.max(),1))} {h}")
        if subcat_counts:
            print(f"\nTop matched subcategories:")
            for name, count in sorted(subcat_counts.items(), key=lambda x: -x[1])[:15]:
                print(f"  {count:4d}  {name}")
    else:
        print("  (no gallery match fields — run detection with object_embeddings.pkl present)")


# ──────────────────────────────────────────────────────────────────────────────
# Main detection loop
# ──────────────────────────────────────────────────────────────────────────────

def process_image(
    img_path: Path,
    gdino_processor,
    gdino_model,
    face_app,
    gallery: dict,
    clip_model=None,
    clip_proc=None,
    object_gallery=None,
) -> dict:
    image = Image.open(img_path).convert("RGB")
    return {
        "image_id": img_path.stem,
        "objects": detect_objects(image, gdino_processor, gdino_model,
                                  clip_model, clip_proc, object_gallery),
        "faces": detect_faces(image, face_app, gallery),
    }


def run_detection(sample: int | None = None, references: str | None = None,
                  limit: int | None = None) -> None:
    gdino_processor, gdino_model = load_gdino()
    face_app = load_face_app()
    try:
        gallery = load_gallery()
    except FileNotFoundError:
        print("WARNING: No gallery found — face detection will run but identities "
              "won't be matched. Run --build-gallery first to enable face recognition.")
        gallery = {}

    # Object gallery (optional): if present, load CLIP once and match every object box.
    object_gallery = load_object_gallery()
    clip_model, clip_proc = load_clip() if object_gallery else (None, None)

    image_paths = sorted(IMAGES_DIR.glob("*.jpg")) + sorted(IMAGES_DIR.glob("*.png"))
    if not image_paths:
        print(f"No images found in {IMAGES_DIR}")
        return
    if references:
        import pandas as pd
        ids = set(pd.read_csv(references)["image_id"].astype(str))
        image_paths = [p for p in image_paths if p.stem in ids]
        print(f"Restricting to {len(image_paths)} images from {references}")
    if limit:
        image_paths = image_paths[:limit]   # first N (matches 04's --limit selection)

    done = {p.stem for p in DETECTIONS_DIR.glob("*.json")}
    remaining = [p for p in image_paths if p.stem not in done]

    if sample:
        remaining = random.sample(remaining, min(sample, len(remaining)))
        print(f"Sample mode: processing {len(remaining)} random images")
    else:
        print(f"{len(done)} already done, {len(remaining)} remaining")

    for img_path in tqdm(remaining):
        try:
            result = process_image(img_path, gdino_processor, gdino_model, face_app, gallery,
                                   clip_model, clip_proc, object_gallery)
            out_path = DETECTIONS_DIR / f"{img_path.stem}.json"
            with open(out_path, "w") as f:
                json.dump(result, f, indent=2)
        except Exception as e:
            print(f"\n  ERROR {img_path.stem}: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Detect political entities in images.")
    parser.add_argument(
        "--sample", type=int, default=None, metavar="N",
        help="Process N random unprocessed images (useful for threshold tuning)",
    )
    parser.add_argument(
        "--eval", action="store_true",
        help="Print match statistics from existing detection JSONs",
    )
    parser.add_argument(
        "--build-gallery", action="store_true",
        help="Rebuild gallery embeddings from data/gallery/*/",
    )
    parser.add_argument(
        "--references", default=None,
        help="CSV with an image_id column; restrict detection to these images",
    )
    parser.add_argument(
        "--limit", type=int, default=None,
        help="Detect only the first N images (after --references filter)",
    )
    args = parser.parse_args()

    if args.build_gallery:
        face_app = load_face_app()
        build_gallery(face_app)
        return

    if args.eval:
        run_eval()
        return

    run_detection(sample=args.sample, references=args.references, limit=args.limit)


if __name__ == "__main__":
    main()
